# Generated by Django 5.2.7 on 2025-10-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='shif',
            new_name='shift',
        ),
    ]
